#cloud-config

groups:
  - docker

write_files:
  - encoding: b64
    content: {{entrypoint_sh_content_encoded}}
    path: "/opt/adguardhome/custom/entrypoint.sh"
    permissions: "0644"

  - encoding: b64
    content: {{adguardhome_yaml_content_encoded}}
    path: "/opt/adguardhome/custom/AdGuardHome.yaml"
    permissions: "0644"

system_info:
  default_user:
    groups: [docker]

mounts:
  # Mount ephemeral storage at resource instead of default /mnt
  - [ephemeral0, /mnt/scratch]

# Install necessary apt packages
packages:
  - docker.io
  - unattended-upgrades
package_update: true
package_upgrade: true

runcmd:
  # Mount all external volumes
  # --------------------------
  - echo ">=== Mounting all external volumes... ===<"
  - grep -v -e '^[[:space:]]*$' /etc/fstab | sed 's|^|  /etc/fstab  |'
  - mount -fav
  - findmnt

final_message: "The system is finally up, after $UPTIME seconds"
