---
- name: Find temporary disk on Azure VM
  ansible.builtin.shell: |
    find /dev/disk/azure -name 'resource-part[0123456789]' | sort | sed -n 1p | xargs readlink -f
  register: search_result
  changed_when: false
  ignore_errors: true

- name: Enable user writing on scratchpad.
  ansible.builtin.file:
    path: /mnt/scratch
    state: directory
    owner: root
    group: root
    mode: "0777"
  when: "search_result.stdout != ''"
